### ISSUE TITLE
[Proposal] Bower Distribution

### ISSUE THREAD

**Issue by rtablada** [skaterdav85/validatorjs#22]
Just started working with this package for client side validations for one of our projects at work.

I know that a lot of users are starting to move to Bower for their client-side asset management.

I am willing to help out to get this package listed on Bower and to create a bower.json file that will just ship the dist folder. Let me know if this is something you would be interested in and I can work up a quick PR for this.

**Comment by MrAtiebatie** [comment]
How are things going with this proposal? Would be very handy indeed :)

**Comment by iamdtang** [comment]
That'd be great! Please send a PR. Sorry I got to this so late. Didn't see it.

**Comment by iamdtang** [comment]
@rtablada you working on this?
