### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jgoux** [skaterdav85/validatorjs#26]
Hello,
Would it be possible to include error messages as an external file or wrap them in an object so we can translate the messages globally and easily swap between langages ?

**Comment by iamdtang** [comment]
Yes that'd be a good feature and it has been on my to-do list for awhile. I'll get to that later today.

**Comment by iamdtang** [comment]
Ive set it up so that you can build the library with other languages. See the README.

**Comment by jgoux** [comment]
Awesome, thanks a lot @skaterdav85 !
I'm making a wrapper of your library for Angular right now. :)

**Comment by iamdtang** [comment]
awesome! let me know when you are done.
