### ISSUE TITLE
Greater than / less than another field

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [skaterdav85/validatorjs#263]
```
unitPrice: 'required|numeric|greater_than:unitCost',
unitCost: 'required|numeric|less_than:unitPrice'
```
Is it possible to do something of the like using the library?

**Comment by dangvanduc90** [comment]
plz tell me, how can i get to it

**Comment by dangvanduc90** [comment]
@AbdelrahmanHafez

**Comment by AbdelrahmanHafez** [comment]
@dangvanduc90 
I don't know if that's possible with validatorjs, as an alternative, you may want to consider using Joi until this is implemented, you can always contribute to the package.
