### ISSUE TITLE
email validation flawed

### ISSUE THREAD

**Issue by Wendtly** [skaterdav85/validatorjs#28]
first.last@example.com doesn't validate.

You currently use /\w+@\w{2,}.\w{2,}/ as your regex, but that won't validate the period ('.'). Refer to this article for a better regex: http://www.regular-expressions.info/email.html

My suggestion (based on that, but allowing some of the newer, longer TLDs, and not requiring uppercasing the string first) is this:

/^[a-zA-Z0-9._-]+@([a-zA-Z0-9.-]+.)+[a-zA-Z]{2,9}$/

**Comment by iamdtang** [comment]
Good catch. Yes it should update to account for that email address. However, that regex above causes the email johndoe@gmail to pass as a valid email. Can you update that regex to account for the ".com" or ".XXX" at the end? You're welcome to send a pull request =)
