### ISSUE TITLE
Attribute Localization

### ISSUE THREAD

**Issue by zeljkohuber** [skaterdav85/validatorjs#305]
How can I localize attributes within error messages? Let's say I have required error message 'This :attribute is required' and I have that message under localization key "REQUIRED_ERROR_MESSAGE". I register that key as language message for 'required' property, but that won't work since key itself is missing :attribute and I'm doing translation on UI using i18next.

Only way I currently see this working is if we had some kind of callback which we can register globally and it would fire upon validation before message is returned in order to change the message. That way I could do this:

```
Validator.setMessageFormatter(function (message, rule, attributes) {
    // localize each attribute because my attributes are also just localization keys
   //  localize message -> e.g. 'This :attribute is required'
   // replace each 'attributes' key if its inside the message so the :attribute would be replaced with 
       localized version
  // return localized message
});
```

Maybe there is some othere way but currently I can't seem to find it.

Thank you.

**Comment by vict-shevchenko** [comment]
In order to provide a custom attribute name, you may want to use [CustomAttributes](https://github.com/skaterdav85/validatorjs#custom-attribute-names) like this:

```
let validator = new Validator({ firstName: '' }, { firstName: 'required' });

validator.setAttributeNames({ firstName: 'Vorname' });
if (validator.fails()) {
  validator.errors.first('firstName'); // "The Vorname field is required."
}
```
If you additionally switch language to `de` - you will have all your error message in a language you want.

**Comment by zeljkohuber** [comment]
@vict-shevchenko I understand that scenario but my situation is something like this (just example): 

`validator.setAttributeNames({ firstName: 'FIRSTNAME_LABEL' });`

where 'FIRSTNAME_LABEL' is the localized key in my localization table. I'm trying to resolve this using setAttributeFormatter but that callback is never called for me. When is this callback invoked? That way I might be able to return localized version of firstName value and resolve my issue.

**Comment by vict-shevchenko** [comment]
If you use `setAttributeNames` you pass an object. Where `key` - is an identifier(attribute name) and `value` sould be already localized string, not a key in your localization table.

when using `setAttributeFormatter` your can achive this trick, but in this case attribute name should be a key in localization table, that may not be usable. 

like this:

```
const localizationTable = {'FIRSTNAME_LABEL' : 'Vorname'};

                                   ⬇️key                   ⬇️key
let validator = new Validator({ FIRSTNAME_LABEL: '' }, { FIRSTNAME_LABEL: 'required' });
validator.setAttributeFormatter(function(attribute) {
  return localizationTable[attribute];
});
if (validator.fails()) {
  console.log(validator.errors.first('FIRSTNAME_LABEL')); // The Vorname field is required.
}
```
