### ISSUE TITLE
Trigger on change validation

### ISSUE THREAD

**Issue by EvenOng** [skaterdav85/validatorjs#31]
HI, 

Let say i have form to validate, how to validate it when trigger on change action without duplicate the code.
Now when click on submit button, can validate all together. 
For sample below, how to just validate email or name when trigger on change.  it is possible to do without duplicate the rules one by one?

Sample: 
var data = {
    name: 'John',
    email: 'johndoe@gmail.com',
    age: 28
};

var rules = {
    name: 'required',
    email: 'required|email',
    age: 'min:18'
};

var validation = new Validator(data, rules);

**Comment by iamdtang** [comment]
You could create 1 object containing all of the rules, and have separate Validator instances for onchange and onsubmit. The rules could for each instance could hook into the master set of rules. For example:

``` js
var rules = {
    name: 'required',
    email: 'required|email',
    age: 'min:18'
};

emailInput.onchange = function() {
    //  hook into the master set of rules just for email
    new Validator({ email: this.value }, { email: rules.email })
};

form.onsubmit = function() {
    // use all the rules
    new Validator(data, rules)
};
```

Does that solve your issue?

**Comment by EvenOng** [comment]
ok i try first. thanks

addition question:
How about when i have 2 form? it is still can hook into the master set of rules when on submit action?

Example:
first form only have "name" and "email"
second form only have "name" and "age"

**Comment by iamdtang** [comment]
Yes the technique above will allow any number of forms. This library is independent of the DOM. So how you construct your Validator instances is really up to you.
