### ISSUE TITLE
How Pass Two values to the async function validations? 

### ISSUE THREAD

**Issue by deepesh0102** [skaterdav85/validatorjs#397]
|                  id  | product_id | lead_id|
| ----------------- | --------------------- |-----------|
| 1  |  1     | 123 |
| 1  | 1      | 124 |

I want to add validation from product_id and lead_id from the leads table. I need to Validate one rule. 

I want to pass two values  (**lead_id**, **product_id**) to this async function for validation. given `lead_id` and `product_id` both exist in table. 

Validator.registerAsync(
  'product_lead_validation',
  (value, args, attribute, passes) => {
   SELECT count(*) FROM leads WHERE product_id = {product_id} AND lead_id != {lead_id}
    passes(false, 'The :attribute has already been taken.'); // It doesn't work!
  }
);

**Comment by mikeerickson** [comment]
@deepeshkumar904 can you share your code how you are invoking this validation?  I have an idea (at least how I handle a similar situation), but I need to see how you are invoking validator before offering a possible solution.

**Comment by mikeerickson** [comment]
@deepeshkumar904 Have you worked past this issue, or do you still need assistance.  If you are good to go, can you please close this issue.
