### ISSUE TITLE
URL Validation edge case when junk character in front of valid URL

### ISSUE THREAD

**Issue by benjamin21st** [skaterdav85/validatorjs#399]
## Example

```javascript
// The following will fail, expected
url = '=mpisx.next/abc.jpg';

// The following will pass, not expected
url = '==sdkdhttps://mpisx.next/abc.jpg';
```

I suspect the issue is within the Regex used here: 
https://github.com/mikeerickson/validatorjs/blob/46928d706054b94821680c089de8b2a185830429/src/rules.js#L260

## Proposed fix
The fix should be as simple as adding the `^` character at beginning of the Regex string.

**Comment by mikeerickson** [comment]
This will be resolved in upcoming 3.5 release
