### ISSUE TITLE
Support attribute placeholder variations

### ISSUE THREAD

**Issue by apih** [skaterdav85/validatorjs#408]
Hi @mikeerickson. For attribute placeholder, Laravel currently support 3 variations, which is `:attribute`, `:ATTRIBUTE` and `:Attribute`. 

Fo reference:
https://github.com/laravel/framework/blob/0c6f5f75bf0ba4d3307145c9d92ae022f60414be/src/Illuminate/Validation/Concerns/FormatsMessages.php#L289

It would be helpful if this library supports such feature as well. Below is the proposed patch that can provide the same feature:

    _replacePlaceholders: function(rule, template, data) {
      var message, attribute;
  
      data.attribute = this._getAttributeName(rule.attribute);
      data.ATTRIBUTE = data.attribute.toLocaleUpperCase();
      data.Attribute = data.attribute.charAt(0).toLocaleUpperCase() + data.attribute.substring(1);
      data[rule.name] = data[rule.name] || rule.getParameters().join(',');
  
      if (typeof template === 'string' && typeof data === 'object') {
        message = template;
  
        for (attribute in data) {
          message = message.replace(new RegExp(':' + attribute, 'g'), data[attribute]);
        }
      }
  
      return message;
    }

**Comment by mikeerickson** [comment]
Hey @apih 

I assume you want to use this in conjunction with `customMessages` for example:

```js
let input = {name: null};
let rules = {name: 'required'};

let validation = new Validator(input, rules, { required: 'You forgot to give a :attribute' });
validation.passes();
validation.errors.first('name'); // returns 'You forgot to give a name'

let validation = new Validator(input, rules, { required: 'You forgot to give a :Attribute' });
validation.passes();
validation.errors.first('name'); // returns 'You forgot to give a Name'

let validation = new Validator(input, rules, { required: 'You forgot to give a :ATTRIBUTE' });
validation.passes();
validation.errors.first('name'); // returns 'You forgot to give a NAME'
```

If this is not what you are looking for, please give me a bit more insight.  

In addition, we are nearing the release of validatorJS 3.5 which will include a new `aliases` feature, which allows you to provide alias names for each attribute.

```js
let data = { fname: "" };
let rules = { fname: "required" };

const validator = new Validator(data, rules, null, null, { fname: "First Name" });
validation.passes();
validation.errors.first('fname'); // returns 'The First Name field is required.'

```

**Comment by apih** [comment]
Yes, your examples demonstrated what I wanted to achieve by adding support for `:attribute` variations. Sorry for not including any examples before.

Basically, I had custom messages that had `:Attribute` placeholder at the start of the sentence in Laravel's translation files, so that the attribute's first letter is capitalized. Since I want to reuse the same custom messages in JavaScript, this feature would be very helpful.

**Comment by mikeerickson** [comment]
I see your point now, makes more sense. Let me marinate on this for a bit, but I don’t see it as something that would cause any issues for existing users, just expanding the internal a bit (like you mentioned in your initial message)

**Comment by apih** [comment]
Thanks @mikeerickson for your consideration.

**Comment by mikeerickson** [comment]
@apih I am curious, are you only needing this functionality, where you supply custom messages, or are you also needing it to support within a custom language file?

I am thinking the implementation will be exposed to all language files, but it will require customizing the associated language file(s).

**Comment by apih** [comment]
I need it to support a custom language file as well. Currently, I am loading the custom language file using `Validator.setMessages()` method.

**Comment by mikeerickson** [comment]
I have completed implementation of this feature and will be part of the upcoming v3.5 release, which I am to release by the end of the week.

**Comment by apih** [comment]
Awesome! 🙂
