### ISSUE TITLE
required_with using multiple fields not working

### ISSUE THREAD

**Issue by nicosetyawanh** [skaterdav85/validatorjs#410]
### Description
`required_with` using multiple fields (example: `required_with:field1,field2`) is not working. It will pass the validation even if the `field1` and/or `field2` is not empty. However, these two codes work:
- `required_with:field1|required_with:field2`
- `required_with:field1`

@mikeerickson Is this an expected behavior?
For now my workaround is to define the rule multiple times like this `required_with:field1|required_with:field2`.

(seems like the same issue with the one raised by @pepijnolivier https://github.com/mikeerickson/validatorjs/issues/323#issuecomment-565030873. I open a new issue since it seems like there are two issues on the same Github issue)

### Version
3.18.1 and 3.22.1

### Code Snippet
https://codesandbox.io/s/validatorjs-requiredwith-array-forked-t5um7?file=/src/Hello.js
(credit to @MikeSuiter, I forked the code posted here https://github.com/mikeerickson/validatorjs/issues/255)

**Comment by mikeerickson** [comment]
@nicosetyawanh Thank you for your report, this issue has been resolved in the upcoming 3.5 release.

**Comment by ghost** [comment]
Thanks! @mikeerickson
