### ISSUE TITLE
validatorjs distributed with let syntax

### ISSUE THREAD

**Issue by tobias-edwards** [skaterdav85/validatorjs#424]
I am using version "3.19.2", validatorjs is being distributed with `let` syntax in the `dist/validator.js` file. This causes backwards compatibility issues with browsers that do not support the syntax: https://caniuse.com/let

Is it expected for us to transpile the package ourselves?

Many thanks

**Comment by mikeerickson** [comment]
I can say, while future versions will be transpiled with build tool, backwards compatibility will be stricter as we being to phase out older browsers. 

We are about to release a new major build and this “should” be resolved with our new build process, but our future plans will dictate further how far back we go

What browser(s) and version(s) are causing issues?

**Comment by tobias-edwards** [comment]
Safari 10, and IE; getting errors like:
- `SyntaxError: Cannot declare a let variable twice: 'e'`
- `SyntaxError: Unexpected identiifier 'e'. expected either 'in' or 'of' in enumeration syntax.`

I have transpiled validatorjs and this has removed the issue (but also introduced some warnings with my Webpack build, but that's another story).
 
Do you have an excpected release date for the new major build?

**Comment by mikeerickson** [comment]
We are very close to final release.  But, I would like to run this build through some extended testing with the browsers you are having issues. 

I can arrange to have a build available that you can test before we do a public release if you wouldn’t mind testing?

**Comment by mikeerickson** [comment]
@tobias-edwards If you would like to test our upcoming release, you can install here.  The latest build removes all use of `let` restoring to previous builds which used `var`

```bash
npm install https://github.com/mikeerickson/validatorjs#next
```

**Comment by mikeerickson** [comment]
Issue resolved with 3.5 release

**Comment by tobias-edwards** [comment]
@mikeerickson sorry for the late reply. Thank you for resolving this, I only have access to Sauce Labs through a colleague's work testing environment so I wouldn't be able to help with testing newer versions

**Comment by mikeerickson** [comment]
@tobias-edwards  no worries, should have a final release ready by end of the week
