### ISSUE TITLE
add support for async/await

### ISSUE THREAD

**Issue by higoka** [skaterdav85/validatorjs#433]
So currently i do something like this if i have an async rule:

```js
app.post('/auth/signup', (req, res) => {
  const validation = new Validator(data, rules)

  function onSuccess () {
    return res.json({ message: 'user successfully created!' })
  }

  function onFailure () {
    return res.status(400).json(validation.errors)
  }

  validation.checkAsync(onSuccess, onFailure)
})
```

In my opinion this is very hard to look at and messy. Instead with proper async/await we could do something like this which is much more readable and cleaner:

```js
app.post('/auth/signup', async (req, res) => {
  const validation = new Validator(data, rules)

  if (await validation.fails()) {
    return res.status(400).json(validation.errors)
  }

  return res.json({ message: 'user successfully created!' })
})
```

Are there any plans for implementing something like this?

**Comment by mikeerickson** [comment]
I am sorry you feel the current version makes your code look hard to read and messy.  Your desired “solution” could be handled if you were to create a simple wrapper method (which is how I do it in my own apps)

Due to existing code, returning a promise from validator / fails (and / or passes) can’t be easily implemented as it would be a breaking change for all our existing users. 

For now, my recommendation would be to create the aforementioned wrapper method.   We have considered the async/await approaching for a future version, but for now the current API will need to remain the same.

**Comment by mikeerickson** [comment]
@higoka FYI, here is how I am using it

Note: The `Validation` class I am referencing is something new in Validator 3.5 (which will be released soon) but in short, it is a class that wraps around the existing validatorjs library and is something that could be created today (it does not need to be part of validatorjs package).




```js
/*-------------------------------------------------------------------------------------------
 * Example using async/await validation module
 * the "Validation" module is custom class, which executes validator methods under the hood
 * -----------------------------------------------------------------------------------------*/

const Validation = require("../dist/Validation");

const data = { fname: "Mike", lname: "Erickson" };
const rules = { fname: "required", lname: "required|min:3" };
const fieldAliases = { fname: "First Name", lname: "Last Name" };

async function testValidator() {
  let result = { status: "pass", messages: {} };
  await new Validation().validate(data, rules, null, null, fieldAliases).catch((error) => {
    result = { status: "fail", messages: { ...error } };
  });


  console.log(result);
}


testValidator();
```


In this example, the console output would contain the default result.  

```bash
{ status: 'pass', messages: {} }
```

If one of the rules were to fail, say not including the `lname` value, the response would be

```bash
{
  status: 'fail',
  messages: { lname: [ 'The Last Name field is required.' ] }
}
```
