### ISSUE TITLE
My email address is in your security policy

### ISSUE THREAD

**Issue by feross** [skaterdav85/validatorjs#439]
My email address is listed in the security policy for this repo. 

https://github.com/mikeerickson/validatorjs/security/policy

Can you remove it since I am getting security emails intended for your team? Thanks!

**Comment by mikeerickson** [comment]
Wow, I had no idea either! Thanks for letting me know, I have no idea why you are in there. 

I will figure out how to a) resolve this issue b) get you removed

**Comment by mikeerickson** [comment]
Updated SECURITY document email contact
