### ISSUE TITLE
Validator.passes() throws an exception when using in AWS Lambda deployed with AWS CDK

### ISSUE THREAD

**Issue by goshoo** [skaterdav85/validatorjs#442]
**What version of this package are you using?**
3.22.1

**What operating system, Node.js, and npm version?**
AWS Lambda with Node.js 14

**What happened?**
I tried to use the package as 

 - const Validator = require('validatorjs');
 - import Validator from 'validatorjs';
 - import * as Validator from 'validatorjs';

and when I send valid values to the validator it works as expected but when I don't pass a required field then I get an exception at

Validator.passes()

**What did you expect to happen?**

I expected Validator.passes() not to throw an exception.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by mikeerickson** [comment]
Can you supply a log of the thrown exception

**Comment by goshoo** [comment]
Hi @mikeerickson ,

I just updated description to include Node.js' version for Lambda. In this Lambda deployment the whole code is in one big file (including libraries).

````
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'def' of undefined",
    "stack": [
        "TypeError: Cannot read property 'def' of undefined",
        "    at Messages._getTemplate (/var/task/index.js:32608:33)",
        "    at Messages.render (/var/task/index.js:32597:29)",
        "    at Validator2._addFailure (/var/task/index.js:32923:33)",
        "    at Validator2.check (/var/task/index.js:32870:20)",
        "    at Validator2.passes (/var/task/index.js:33128:21)",
        "    at Runtime.handler (/var/task/index.js:33219:18)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

**Comment by mikeerickson** [comment]
The issue is related to missing language files. How are you building this `index.js` file? 

 Since the plugin is not reading from `node_modules` where the language files would exist normally, you are receiving this error.

**Comment by goshoo** [comment]
AWS CDK builds the files. I guess it's something similar to esbuild.

I install NPM packages with npm but the Lambda's source is only one big file  with all its dependencies - approximately 33 000 lines in this example.

**Comment by mikeerickson** [comment]
My guess is that it is not bundling the language files used internally

**Comment by goshoo** [comment]
Maybe I'll be able to prepare a demo this weekend. What do you think?

**Comment by mikeerickson** [comment]
Sounds good, I will have a look and see what can be done.  What language do you use for your tests (I guess it doesn’t totally matter since it is in lamda)

**Comment by goshoo** [comment]
I'm going to use JavaScript but TypeScript could be an option, too.

**Comment by mikeerickson** [comment]
Hello, my apologies, I am referring to which spoken language do you use for validator messages (not development language)

**Comment by goshoo** [comment]
I use English.

**Comment by goshoo** [comment]
Hi @mikeerickson ,

AWS CDK uses esbuild and it seems that this is the problem. I wrote simple program in Node.js and validatorjs works properly but if I use esbuild for this program then the same error appears when data is invalid according the rules in the program.

Here is the program in Node.js

```js
'use strict';

const Validator = require('validatorjs');

const myArgs = process.argv.slice(2);

const data = {
    username: myArgs[0],
    password: myArgs[1]
};

const rules = {
    username: 'required|string',
    password: 'integer'
};

const val = new Validator(data, rules);
const res = val.passes();

console.log(`Valid: ${res}`);
```

**Comment by goshoo** [comment]
Hi again!

The issue with AWS Lambda was my mistake with bundling. Here the correct code:

```js
const lam = new lambdaNode.NodejsFunction(this, 'route', {
      entry: path.join(__dirname, `/lambda/lambda.ts`),
      runtime: lambda.Runtime.NODEJS_14_X,
      memorySize: 1024,
      timeout: cdk.Duration.seconds(5),
      handler: 'handler',
      bundling: {
        nodeModules: ['validatorjs'],
      }
    });
```

The mistake is that I had not included "bundling" section with "validatorjs" module.

So I'm closing this issue report and I'm sorry for the noise.

**Comment by mikeerickson** [comment]
Thanks for sharing what the actual problem was, and solution.  It will be good to have as archival information
