### ISSUE TITLE
Other validations are being ignored when value is null

### ISSUE THREAD

**Issue by feeh27** [skaterdav85/validatorjs#446]
**What version of this package are you using?**
3.22.1

**What operating system, Node.js, and npm version?**
**OS**: Ubuntu
**Node:** v12.22.3
**NPM**: 7.20.5
**Yarn**: 1.22.17

**What happened?**
When I send a null value, validations are ignored and the value is accepted, only when there is a validation of type "required" that the value is not accepted.

**What did you expect to happen?**
Check all rules and stop only in case of failure.

**Are you willing to submit a pull request to fix this bug?**
Yes

I found where it's necessary to intercept, `src/validator.js` file:

https://github.com/mikeerickson/validatorjs/blob/46928d706054b94821680c089de8b2a185830429/src/validator.js#L67-L69

Change to:

```javascript
 if (inputValue !== null && !this._isValidatable(rule, inputValue)) { 
   continue; 
 } 
```

**Comment by feeh27** [comment]
I found that this change is causing other errors.

I found a safer alternative, but due to the delay of the person responsible for this repository in a return in #447, I will not submit the code.

I will continue these treatments only on my fork in case anyone is interested.

**Comment by NorthBlue333** [comment]
Hey @feeh27 
This is due to implicit rules. See the docs here: https://github.com/mikeerickson/validatorjs#available-rules

For custom rules, you can use `registerImplicit` instead of `register` (see the source code).

Also, Laravel works similarly: https://laravel.com/docs/9.x/validation#implicit-rules

**Comment by feeh27** [comment]
> Hey @feeh27 This is due to implicit rules. See the docs here: https://github.com/mikeerickson/validatorjs#available-rules
> 
> For custom rules, you can use `registerImplicit` instead of `register` (see the source code).
> 
> Also, Laravel works similarly: https://laravel.com/docs/9.x/validation#implicit-rules

This worked for me, thanks @NorthBlue333
