### ISSUE TITLE
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'messages.def')]

### ISSUE THREAD

**Issue by kharysharpe** [skaterdav85/validatorjs#454]
Leaving this here for others who might have this issue  (Noticed it when using Laravel, Vitejs and VueJs )

Add: `Validator.setMessages('en', en);`

```
import Validator from 'validatorjs';
import en from 'validatorjs/src/lang/en';

Validator.setMessages('en', en);

const validation = new Validator(data, rules);
```

**Comment by jaxramus** [comment]
omg THANK YOU this was driving me ape shit

**Comment by envatic** [comment]
What happens if you use multi language app?
