### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'def')

### ISSUE THREAD

**Issue by envatic** [skaterdav85/validatorjs#455]
**What version of this package are you using?**
"validatorjs": "^3.22.1",
**What operating system, Node.js, and npm version?**
npm: 8.13.2 nodejs:v18.6.0

**What happened?**
```js
const data = {
    "currency": 97,
    "action": "buy",
    "all": false,
    "gateway": 1,
    "banks_name": ""
}
const rules = {
    "currency": "required|numeric",
    "gateway": "required|numeric",
    "action": "required|in:buy,sell",
    "all": "required|boolean",
    "bank_name": "required|string"
}
const messages = {
    "required.currency": "Please choose your currency",
    "required.country": "Please select a country",
    "required.gateway": "Please choose your payment method"
}
const validation = new Validator(data, rules, messages);
 if (validation.passes()) return true;
```
This causes error:
```js
runtime-core.esm-bundler.js:218 Uncaught TypeError: Cannot read properties of undefined (reading 'def')
    at Messages._getTemplate (messages.js:103:29)
    at Messages.render (messages.js:82:25)
    at Validator._addFailure (validator.js:151:29)
    at Validator.check (validator.js:73:16)
    at Validator.passes (validator.js:497:17)
```
**What did you expect to happen?**
Should validate as expected
**Are you willing to submit a pull request to fix this bug?**
No

**Comment by envatic** [comment]
**I was using `vite`.**
 It seems the language files never gets imported.
I tried importing the lang file from `node_modules/validatorjs/src/lang/en` or from `validatorjs/src/lang/en` in vain
I got a  error about `undefined module in file...`
In the end copied the language files to folder in my project root modified them to use export default
```js
export default {
```
instead of 
```js
module.exports = {
````
**In the end was able to make it work!**
and dynamically import the language files from there
```js
 const lang = document.documentElement.lang.substring(0, 2);
    console.log(`lang`, lang);
    const language = await import(`../../../validator/${lang}`);
    Validator.setMessages(lang.value, language);
    const validation = new Validator(data, rules, messages);
    if (validation.passes()) return true;
```

its a bit hacky  but I will close this as its resolved

**Comment by gregfenton** [comment]
I don't see this as a valid solution.

I am running into the same issue using Vite with React v18.1.

I am able to repro this issue with:

- `npm create vite@latest my-vite-react-app -- --template react`
- `cd my-vite-react-app`
- `npm install`
- `npm install validatorjs`
- replace the contents of `src/App.jsx` with the following:
   ```jsx
   import { useState } from 'react';
   import './App.css';
   import Validator from 'validatorjs';
   
   const rules = { city: 'required', province: 'required' };
   const goodData = { city: 'Toronto', province: 'Ontario' };
   const badData = { city: undefined, province: 'Ontario' };
   
   export const App = () => {
     const [isValid, setIsValid] = useState();
   
     const doValid = () => setIsValid(new Validator(goodData, rules).passes());
     const doInvalid = () => setIsValid(new Validator(badData, rules).passes());
   
     return (
       <div className='App'>
         <h2>Is valid: {isValid ? 'true' : 'false'} </h2>
         <div>
           <button onClick={doValid}> VALID </button>{' '}
           <button onClick={doInvalid}> INVALID </button>
         </div>
       </div>
     );
   };
   ```
- `npm run dev`
- in your browser, click the VALID button and see that "Is valid: true` displays
- click INVALID button and check the browser's JS console. You will see the same exception as reported initially.
